### ISSUE TITLE
Becoming a maintainer?

### ISSUE THREAD

**Issue by danielcompton** [danielcompton/clojure-postmark#7]
Hi there

Re: http://stevelosh.com/projects/

We use clojure-postmark actively in production and have our own fork. I'd be happy to be maintainer on the main project and merge our improvements back in. Does that work for you?

**Comment by sjl** [comment]
Hi, yes I'm still looking for a maintainer.  Basically my requests for a future maintainer are:

* Don't change the license
* Keep using semantic versioning
* Try to keep backwards compatibility whenever possible
* Update the changelog when you release a new version
* Keep the documentation up to date when you change things

The docs are currently rendered with my own doc tool: https://github.com/sjl/d but I don't care if you port them to something else (it should be easy with Pandoc or something because they're just Markdown files).  I also host them on my Bitbucket static pages repo thing, so you'd probably want to move them somewhere else.

Right now I primarily use Mercurial & Bitbucket, and maintain a Git mirror with hg-git.  I won't be heartbroken if you switch to using GitHub alone though.

I can either add you as a contributor to the repo, or you can fork it and I can make one last commit to my README pointing people at the new location.

Let me know what you want to do, and thanks!

**Comment by danielcompton** [comment]
> Basically my requests for a future maintainer are:

Yep, all fine.

> I also host them on my Bitbucket static pages repo thing, so you'd probably want to move them somewhere else.

Yeah, probably Github static pages.

> I won't be heartbroken if you switch to using GitHub alone though.

Whew, I'd probably aim to use GitHub :)

> or you can fork it and I can make one last commit to my README pointing people at the new location.

Forking is probably easiest, as I don't think you can give someone else admin permissions on a personal repo (for things like CI, settings, adding contributors). https://github.com/danielcompton/clojure-postmark

Would you be ok with adding me as a committer of the postmark artefact on Clojars too?

**Comment by danielcompton** [comment]
Actually, transferring ownership is probably the best, as watchers and history transfer along too:

**Comment by sjl** [comment]
> Would you be ok with adding me as a committer of the postmark artefact on Clojars too?

Yes, what's your username there?

Transferring sounds right, except that on the help page it says:

> The target account must not have a repository with the same name, or a fork in the same network.

So you might need to delete your fork first?  Not sure how this will work with your existing PRs... you might need to store them locally and merge them back once I transfer it.

**Comment by danielcompton** [comment]
> Yes, what's your username there?

https://clojars.org/users/danielcompton

> So you might need to delete your fork first?

Cool, I've just done this now.

**Comment by danielcompton** [comment]
I've moved everything over, so I'll close this now. Thanks heaps!
